ViewModels/RealizarCompraViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.Models;

namespace Trabalho1Bim.ViewModels
{
    public class RealizarCompraViewModel
    {
        public List<SelectListItem> ListaProdutos { get; set; }
        public List<SelectListItem> ListaFornecedores { get; set; }

        [Required]
        [Display(Name = "Produto")]
        public int ProdutoId { get; set; }

        [Required]
        [Display(Name = "Fornecedor")]
        public int FornecedorId { get; set; }

        [Required]
        public int Quantidade { get; set; }

        public List<SelectListItem> CriarListaFornecedores(List<Fornecedor> listaFornecedores)
        {
            var retorno = listaFornecedores.Select(x =>
                new SelectListItem()
                {
                    Text = x.nome,
                    Value = x.idFornecedor.ToString()
                }).ToList();
            return retorno;
        }

        public List<SelectListItem> CriarListaProdutos(List<Produto> listaProdutos)
        {
            var retorno = listaProdutos.Select(x =>
                new SelectListItem()
                {
                    Text = x.nome,
                    Value = x.idProduto.ToString()
                }).ToList();
            return retorno;
        }
    }
}

Controllers/RealizarCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.DP;
using Trabalho1Bim.ViewModels;

namespace Trabalho1Bim.GT
{
    public class RealizarCompraController : Controller
    {
        RealizarCompraViewModel realizarCompraViewModel = new RealizarCompraViewModel();
        ProdutoDP produtoDP = new ProdutoDP();
        FornecedorDP fornecedorDP = new FornecedorDP();
        CompraFacadeDP facadeDP = new CompraFacadeDP();
        // GET: RealizarCompra
        public ActionResult Index()     
        {
            realizarCompraViewModel.ListaProdutos = realizarCompraViewModel.CriarListaProdutos(produtoDP.Repository.RecuperarTodos().ToList());
            realizarCompraViewModel.ListaFornecedores = realizarCompraViewModel.CriarListaFornecedores(fornecedorDP.Repository.RecuperarTodos().ToList());
            return View(realizarCompraViewModel);
        }
        [HttpPost]
        public ActionResult Index(RealizarCompraViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    facadeDP.RealizarCompra(model.FornecedorId, model.ProdutoId, model.Quantidade);
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View(model);
        }
    }
}

Views/RealizarCompra/Index.cshtml
@using Trabalho1Bim.ViewModels
@using Trabalho1Bim.Controllers
@model RealizarCompraViewModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h2>Realizar Compra</h2>
    @using (Html.BeginForm("Index", "RealizarCompra", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.FornecedorId)
            @Html.DropDownListFor(m => m.FornecedorId, Model.ListaFornecedores, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoId)
            @Html.DropDownListFor(m => m.ProdutoId, Model.ListaProdutos, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade)
            @Html.TextBoxFor(m => m.Quantidade, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-success">Realizar Compra</button>
    }
    @Html.ValidationSummary()
</body>
</html>