Controllers/EstornarVendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.DP;
using Trabalho1Bim.GD;
using Trabalho1Bim.Models;
using Trabalho1Bim.ViewModels;

namespace Trabalho1Bim.Controllers
{
    public class EstornarVendaController : Controller
    {
        EstornarVendaViewModel estornarVendaViewModel = new EstornarVendaViewModel();
        VendaDP vendaDP = new VendaDP();

        // GET: ManterCliente
        public ActionResult Index()
        {
            estornarVendaViewModel.ListaVenda = vendaDP.Repository.RecuperarTodos().ToList();
            return View(estornarVendaViewModel);
        }
        
        public ActionResult Estornar(int vendaId)
        {
            estornarVendaViewModel.ListaVenda = vendaDP.Repository.RecuperarTodos().ToList();
            if (ModelState.IsValid)
            {
                try
                {
                    new VendaDP().EstornarVenda(vendaId);
                    return View("Index", estornarVendaViewModel);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View("Index", estornarVendaViewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/3/paper/bootstrap.min.css">
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li  class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Cadastros Gerais
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Manter Cliente", "Index", "ManterCliente")</li>
                            <li>@Html.ActionLink("Manter Produto", "Index", "ManterProduto")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Vendas
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Realizar Venda", "Index", "RealizarVenda")</li>
                            <li>@Html.ActionLink("Estornar Venda", "Index", "EstornarVenda")</li>
                            <li>@Html.ActionLink("Relatório Venda", "Index", "RelatorioVenda")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Compras
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Realizar Compra", "Index", "RealizarCompra")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - UVV - Engenharia de Software II</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>