ViewModels/RelatorioVendaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.Models;

namespace Trabalho1Bim.ViewModels
{
    public class RelatorioVendaViewModel
    {
        public List<SelectListItem> ListaVendedores { get; set; }
        public List<Venda> ListaVenda { get; set; } = new List<Venda>();
        public int VendedorId { get; set; }

        public List<SelectListItem> CriarListaVendedores(List<Vendedor> listaVendedores)
        {
            var retorno = listaVendedores.Select(x =>
                new SelectListItem()
                {
                    Text = x.nome,
                    Value = x.idPessoa.ToString()
                }).ToList();
            return retorno;
        }
    }
}

Controllers/RelatorioVendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.DP;
using Trabalho1Bim.GD;
using Trabalho1Bim.Models;
using Trabalho1Bim.ViewModels;

namespace Trabalho1Bim.Controllers
{
    public class RelatorioVendaController : Controller
    {
        RelatorioVendaViewModel relatorioVendaViewModel = new RelatorioVendaViewModel();
        VendedorDP vendedorDP = new VendedorDP();
        VendaDP vendaDP = new VendaDP();

        // GET: ManterCliente
        public ActionResult Index()
        {
            relatorioVendaViewModel.ListaVendedores = relatorioVendaViewModel.CriarListaVendedores(vendedorDP.Repository.RecuperarTodos().ToList());
            relatorioVendaViewModel.ListaVenda = vendaDP.Repository.RecuperarTodos().ToList();
            return View(relatorioVendaViewModel);
        }

        [HttpPost]
        public ActionResult Index(RelatorioVendaViewModel model)
        {
            relatorioVendaViewModel.ListaVendedores = relatorioVendaViewModel.CriarListaVendedores(vendedorDP.Repository.RecuperarTodos().ToList());
            relatorioVendaViewModel.ListaVenda = vendaDP.Repository.RecuperarPorVendedor(model.VendedorId);
            return View(relatorioVendaViewModel);
        }
    }
}

Views/RelatorioVenda/Index.cshtml
@using Trabalho1Bim.ViewModels
@model RelatorioVendaViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Relatório Venda</h2>
@using (Html.BeginForm("Index", "RelatorioVenda", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.VendedorId)
        @Html.DropDownListFor(m => m.VendedorId, Model.ListaVendedores, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-success">Filtrar</button>
}
<table id="tableRelatorioVenda" class="table table-striped">
    <thead>
        <tr>
            <th>Cliente</th>
            <th>Vendedor</th>
            <th>Data</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var venda in Model.ListaVenda)
        {
            <tr>
                <td>@venda.Cliente.nome</td>
                <td>@venda.Vendedor.nome</td>
                <td>@venda.data</td>
            </tr>
        }
    </tbody>
</table>