ViewModels/RealizarVendaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.Models;

namespace Trabalho1Bim.ViewModels
{
    public class RealizarVendaViewModel
    {
        public List<SelectListItem> ListaProdutos { get; set; }
        public List<SelectListItem> ListaClientes { get; set; }
        public List<SelectListItem> ListaVendedores { get; set; }

        [Required]
        [Display(Name = "Produto")]
        public int ProdutoId { get; set; }

        [Required]
        [Display(Name = "Cliente")]
        public int ClienteId { get; set; }

        [Required]
        [Display(Name = "Vendedor")]
        public int VendedorId { get; set; }

        [Required]
        public int Quantidade { get; set; }

        public List<SelectListItem> CriarListaClientes(List<Cliente> listaClientes)
        {
            var retorno = listaClientes.Select(x =>
                new SelectListItem()
                {
                    Text = x.nome,
                    Value = x.idPessoa.ToString()
                }).ToList();
            return retorno;
        }

        public List<SelectListItem> CriarListaVendedores(List<Vendedor> listaVendedores)
        {
            var retorno = listaVendedores.Select(x =>
                new SelectListItem()
                {
                    Text = x.nome,
                    Value = x.idPessoa.ToString()
                }).ToList();
            return retorno;
        }

        public List<SelectListItem> CriarListaProdutos(List<Produto> listaProdutos)
        {
            var retorno = listaProdutos.Select(x =>
                new SelectListItem()
                {
                    Text = x.nome,
                    Value = x.idProduto.ToString()
                }).ToList();
            return retorno;
        }
    }
}

Controllers/RealizarVendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabalho1Bim.DP;
using Trabalho1Bim.ViewModels;

namespace Trabalho1Bim.GT
{
    public class RealizarVendaController : Controller
    {
        RealizarVendaViewModel realizarVendaViewModel = new RealizarVendaViewModel();
        VendaFacadeDP facadeDP = new VendaFacadeDP();
        ClienteDP clienteDP = new ClienteDP();
        ProdutoDP produtoDP = new ProdutoDP();
        VendedorDP vendedorDP = new VendedorDP();
        // GET: RealizarCompra
        public ActionResult Index()
        {
            realizarVendaViewModel.ListaProdutos = realizarVendaViewModel.CriarListaProdutos(produtoDP.Repository.RecuperarTodos().ToList());
            realizarVendaViewModel.ListaClientes = realizarVendaViewModel.CriarListaClientes(clienteDP.Repository.RecuperarTodos().ToList());
            realizarVendaViewModel.ListaVendedores = realizarVendaViewModel.CriarListaVendedores(vendedorDP.Repository.RecuperarTodos().ToList());
            return View(realizarVendaViewModel);
        }
        [HttpPost]
        public ActionResult Index(RealizarVendaViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    facadeDP.RealizarVenda(model.ClienteId, model.VendedorId, model.ProdutoId, model.Quantidade);
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            model.ListaProdutos = realizarVendaViewModel.CriarListaProdutos(produtoDP.Repository.RecuperarTodos().ToList());
            model.ListaClientes = realizarVendaViewModel.CriarListaClientes(clienteDP.Repository.RecuperarTodos().ToList());
            model.ListaVendedores = realizarVendaViewModel.CriarListaVendedores(vendedorDP.Repository.RecuperarTodos().ToList());
            return View(model);
        }
    }
}

Views/RealizarVenda/Index.cshtml
@using Trabalho1Bim.ViewModels
@using Trabalho1Bim.Controllers
@model RealizarVendaViewModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h2>Realizar Venda</h2>
    @using (Html.BeginForm("Index", "RealizarVenda", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId)
            @Html.DropDownListFor(m => m.ClienteId, Model.ListaClientes, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.VendedorId)
            @Html.DropDownListFor(m => m.VendedorId, Model.ListaVendedores, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoId)
            @Html.DropDownListFor(m => m.ProdutoId, Model.ListaProdutos, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade)
            @Html.TextBoxFor(m => m.Quantidade, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-success">Realizar Compra</button>
    }
    @Html.ValidationSummary()
</body>
</html>